/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ids.ops.escrow.security.login;

import com.ids.ops.escrow.security.connections.DatabaseOperations;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author paul20
 */
public class PassRecovery extends javax.swing.JFrame {

    /**
     * Creates new form PassRecovery
     */
    public PassRecovery() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contentpane = new javax.swing.JPanel();
        header = new javax.swing.JPanel();
        pagetitle = new javax.swing.JLabel();
        body = new javax.swing.JPanel();
        pwdrecovery = new javax.swing.JPanel();
        instructions = new javax.swing.JLabel();
        username = new javax.swing.JLabel();
        usernamefield = new javax.swing.JTextField();
        email = new javax.swing.JLabel();
        emailfield = new javax.swing.JTextField();
        lastname = new javax.swing.JLabel();
        lastnamefield = new javax.swing.JTextField();
        firstname = new javax.swing.JLabel();
        firstnamefield = new javax.swing.JTextField();
        resetpwd = new javax.swing.JButton();
        footer = new javax.swing.JPanel();
        statlabel = new javax.swing.JLabel();
        statusbar = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        contentpane.setBackground(new java.awt.Color(229, 234, 237));
        contentpane.setMaximumSize(new java.awt.Dimension(400, 350));
        contentpane.setMinimumSize(new java.awt.Dimension(400, 300));
        contentpane.setPreferredSize(new java.awt.Dimension(400, 350));

        header.setBackground(new java.awt.Color(229, 234, 237));
        header.setMaximumSize(new java.awt.Dimension(400, 65));
        header.setMinimumSize(new java.awt.Dimension(400, 65));

        pagetitle.setBackground(new java.awt.Color(229, 234, 237));
        pagetitle.setFont(new java.awt.Font("Arial", 3, 16)); // NOI18N
        pagetitle.setForeground(new java.awt.Color(121, 123, 128));
        pagetitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pagetitle.setText("Account Recovery: Password Reset");
        pagetitle.setMaximumSize(new java.awt.Dimension(380, 43));
        pagetitle.setMinimumSize(new java.awt.Dimension(380, 43));
        pagetitle.setPreferredSize(new java.awt.Dimension(380, 43));

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pagetitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pagetitle, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        body.setBackground(new java.awt.Color(229, 234, 237));
        body.setMaximumSize(new java.awt.Dimension(400, 229));
        body.setMinimumSize(new java.awt.Dimension(400, 229));

        pwdrecovery.setBackground(new java.awt.Color(229, 234, 237));

        instructions.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        instructions.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        instructions.setText("Please complete the fields below to reset your password:");

        username.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        username.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        username.setText("Username:");
        username.setMaximumSize(new java.awt.Dimension(100, 30));
        username.setMinimumSize(new java.awt.Dimension(100, 30));
        username.setPreferredSize(new java.awt.Dimension(100, 30));

        usernamefield.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        usernamefield.setMaximumSize(new java.awt.Dimension(165, 30));
        usernamefield.setMinimumSize(new java.awt.Dimension(165, 30));
        usernamefield.setPreferredSize(new java.awt.Dimension(165, 30));

        email.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        email.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        email.setText("Email Address:");
        email.setMaximumSize(new java.awt.Dimension(100, 30));
        email.setMinimumSize(new java.awt.Dimension(100, 30));
        email.setPreferredSize(new java.awt.Dimension(100, 30));

        emailfield.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        emailfield.setMaximumSize(new java.awt.Dimension(165, 30));
        emailfield.setMinimumSize(new java.awt.Dimension(165, 30));
        emailfield.setPreferredSize(new java.awt.Dimension(165, 30));

        lastname.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lastname.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lastname.setText("Last Name:");
        lastname.setMaximumSize(new java.awt.Dimension(100, 30));
        lastname.setMinimumSize(new java.awt.Dimension(100, 30));
        lastname.setPreferredSize(new java.awt.Dimension(100, 30));

        lastnamefield.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        lastnamefield.setMaximumSize(new java.awt.Dimension(165, 30));
        lastnamefield.setMinimumSize(new java.awt.Dimension(165, 30));
        lastnamefield.setPreferredSize(new java.awt.Dimension(165, 30));

        firstname.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        firstname.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        firstname.setText("First Name:");
        firstname.setMaximumSize(new java.awt.Dimension(100, 30));
        firstname.setMinimumSize(new java.awt.Dimension(100, 30));
        firstname.setPreferredSize(new java.awt.Dimension(100, 30));

        firstnamefield.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        firstnamefield.setMaximumSize(new java.awt.Dimension(165, 30));
        firstnamefield.setMinimumSize(new java.awt.Dimension(165, 30));
        firstnamefield.setPreferredSize(new java.awt.Dimension(165, 30));

        resetpwd.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        resetpwd.setText("Reset Password");
        resetpwd.setMaximumSize(new java.awt.Dimension(130, 25));
        resetpwd.setMinimumSize(new java.awt.Dimension(130, 25));
        resetpwd.setPreferredSize(new java.awt.Dimension(130, 25));
        resetpwd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                resetpwdMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pwdrecoveryLayout = new javax.swing.GroupLayout(pwdrecovery);
        pwdrecovery.setLayout(pwdrecoveryLayout);
        pwdrecoveryLayout.setHorizontalGroup(
            pwdrecoveryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pwdrecoveryLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(pwdrecoveryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(instructions, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pwdrecoveryLayout.createSequentialGroup()
                        .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(usernamefield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pwdrecoveryLayout.createSequentialGroup()
                        .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(emailfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pwdrecoveryLayout.createSequentialGroup()
                        .addGroup(pwdrecoveryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lastname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(firstname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pwdrecoveryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(firstnamefield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lastnamefield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(resetpwd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pwdrecoveryLayout.setVerticalGroup(
            pwdrecoveryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pwdrecoveryLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(instructions)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pwdrecoveryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(usernamefield, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pwdrecoveryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailfield, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pwdrecoveryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lastname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lastnamefield, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pwdrecoveryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstnamefield, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(firstname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(resetpwd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout bodyLayout = new javax.swing.GroupLayout(body);
        body.setLayout(bodyLayout);
        bodyLayout.setHorizontalGroup(
            bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bodyLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pwdrecovery, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        bodyLayout.setVerticalGroup(
            bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bodyLayout.createSequentialGroup()
                .addComponent(pwdrecovery, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        footer.setBackground(new java.awt.Color(229, 234, 237));

        statusbar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        statusbar.setStringPainted(true);

        javax.swing.GroupLayout footerLayout = new javax.swing.GroupLayout(footer);
        footer.setLayout(footerLayout);
        footerLayout.setHorizontalGroup(
            footerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, footerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(statlabel, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(statusbar, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        footerLayout.setVerticalGroup(
            footerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(footerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(footerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(statusbar, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                    .addComponent(statlabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout contentpaneLayout = new javax.swing.GroupLayout(contentpane);
        contentpane.setLayout(contentpaneLayout);
        contentpaneLayout.setHorizontalGroup(
            contentpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentpaneLayout.createSequentialGroup()
                .addGroup(contentpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(body, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(footer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        contentpaneLayout.setVerticalGroup(
            contentpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentpaneLayout.createSequentialGroup()
                .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(body, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(footer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contentpane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contentpane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void resetpwdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resetpwdMouseClicked
        String firstname = firstnamefield.getText();
        String lastname = lastnamefield.getText();
        String email = emailfield.getText();
        String username = usernamefield.getText();
        Thread resetpwd = new Thread(new Runnable() {
            @Override
            public void run() {
                DatabaseOperations dbops = new DatabaseOperations();
                try {
                    dbops.resetPassword(username, email, lastname, firstname, statusbar,statlabel);
                } catch (InterruptedException ex) {
                    Logger.getLogger(PassRecovery.class.getName()).log(Level.SEVERE, null, ex);
                }

            }
        });
        resetpwd.start();
        if(statusbar.getString().equals("100%")){
            this.dispose();
        }
    }//GEN-LAST:event_resetpwdMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PassRecovery.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PassRecovery.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PassRecovery.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PassRecovery.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PassRecovery().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel body;
    private javax.swing.JPanel contentpane;
    private javax.swing.JLabel email;
    private javax.swing.JTextField emailfield;
    private javax.swing.JLabel firstname;
    private javax.swing.JTextField firstnamefield;
    private javax.swing.JPanel footer;
    private javax.swing.JPanel header;
    private javax.swing.JLabel instructions;
    private javax.swing.JLabel lastname;
    private javax.swing.JTextField lastnamefield;
    private javax.swing.JLabel pagetitle;
    private javax.swing.JPanel pwdrecovery;
    private javax.swing.JButton resetpwd;
    private javax.swing.JLabel statlabel;
    private javax.swing.JProgressBar statusbar;
    private javax.swing.JLabel username;
    private javax.swing.JTextField usernamefield;
    // End of variables declaration//GEN-END:variables
}
