/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ids.ops.escrow.uix.modules;

import com.ids.ops.escrow.security.connections.DatabaseOperations;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import javax.swing.Timer;
import com.ids.ops.escrow.security.validation.InputValidation;
import com.ids.ops.escrow.security.UserPermissions;
import com.ids.ops.escrow.security.UserPermissions;
import com.ids.ops.escrow.security.encryption.EncryptPassword;
import com.ids.ops.escrow.security.encryption.EncodePermissions;
import com.ids.ops.escrow.security.gatekeeper.MailerSubsystem;
import com.ids.ops.escrow.uix.OperationsMenu;
import java.awt.Color;
import java.util.TreeMap;
import javax.swing.JFrame;


/**
 *
 * @author paul20
 */
public class AddUser extends javax.swing.JFrame {

    /**
     * Creates new form AddUser
     */
    public AddUser() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        innercontent = new javax.swing.JPanel();
        header = new javax.swing.JPanel();
        pagetitle = new javax.swing.JLabel();
        idslogo = new javax.swing.JLabel();
        body = new javax.swing.JPanel();
        userinfo = new javax.swing.JPanel();
        userinfoheader = new javax.swing.JPanel();
        infotitle = new javax.swing.JLabel();
        userinfodata = new javax.swing.JPanel();
        basicinfo = new javax.swing.JPanel();
        firstname = new javax.swing.JLabel();
        fnmfield = new javax.swing.JTextField();
        lastname = new javax.swing.JLabel();
        lnmfield = new javax.swing.JTextField();
        advinfo = new javax.swing.JPanel();
        username = new javax.swing.JLabel();
        unmfield = new javax.swing.JTextField();
        passwd = new javax.swing.JLabel();
        pwdfield = new javax.swing.JPasswordField();
        cpasswd = new javax.swing.JLabel();
        cpwdfield = new javax.swing.JPasswordField();
        email = new javax.swing.JLabel();
        emlfield = new javax.swing.JTextField();
        othinfo = new javax.swing.JPanel();
        teamlabel = new javax.swing.JLabel();
        otherinfo = new javax.swing.JComboBox<>();
        clrusrdata = new javax.swing.JButton();
        chkpassword = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        userperm = new javax.swing.JPanel();
        permheader = new javax.swing.JPanel();
        permtitle = new javax.swing.JLabel();
        permdata = new javax.swing.JPanel();
        usrstatlabel = new javax.swing.JLabel();
        userstatus = new javax.swing.JComboBox<>();
        actflglabel = new javax.swing.JLabel();
        acctflags = new javax.swing.JComboBox<>();
        jSeparator4 = new javax.swing.JSeparator();
        prmdatalabel = new javax.swing.JLabel();
        permlist = new javax.swing.JScrollPane();
        permissionlist = new javax.swing.JList<>();
        permdisplay = new javax.swing.JTextField();
        permpreview = new javax.swing.JLabel();
        permview = new javax.swing.JScrollPane();
        encodedperm = new javax.swing.JTextArea();
        btnpanel = new javax.swing.JPanel();
        inputvalidate = new javax.swing.JButton();
        returntomain = new javax.swing.JButton();
        submitinfo = new javax.swing.JButton();
        previewprm = new javax.swing.JButton();
        clrprmdata = new javax.swing.JButton();
        usrprmhelp = new javax.swing.JButton();
        footer = new javax.swing.JPanel();
        userstatusBar = new javax.swing.JToolBar();
        statbarDate = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        statbarTime = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        dispUsername = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("User Operations");
        setBackground(new java.awt.Color(229, 234, 237));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setResizable(false);

        innercontent.setBackground(new java.awt.Color(229, 234, 237));
        innercontent.setMaximumSize(new java.awt.Dimension(800, 600));
        innercontent.setMinimumSize(new java.awt.Dimension(800, 600));
        innercontent.setPreferredSize(new java.awt.Dimension(800, 600));

        header.setBackground(new java.awt.Color(229, 234, 237));
        header.setMaximumSize(new java.awt.Dimension(790, 65));
        header.setMinimumSize(new java.awt.Dimension(790, 65));
        header.setName(""); // NOI18N
        header.setPreferredSize(new java.awt.Dimension(790, 65));

        pagetitle.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        pagetitle.setForeground(new java.awt.Color(121, 123, 128));
        pagetitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pagetitle.setText("IDS Operations: Escrow - User Menu");
        pagetitle.setMaximumSize(new java.awt.Dimension(730, 65));
        pagetitle.setMinimumSize(new java.awt.Dimension(730, 65));
        pagetitle.setPreferredSize(new java.awt.Dimension(730, 65));

        idslogo.setBackground(new java.awt.Color(229, 234, 237));
        idslogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/IDSColor.jpg"))); // NOI18N
        idslogo.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        idslogo.setMaximumSize(new java.awt.Dimension(240, 65));
        idslogo.setMinimumSize(new java.awt.Dimension(240, 65));
        idslogo.setPreferredSize(new java.awt.Dimension(240, 65));

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addComponent(pagetitle, javax.swing.GroupLayout.PREFERRED_SIZE, 554, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(idslogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pagetitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(idslogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        body.setBackground(new java.awt.Color(229, 234, 237));
        body.setMaximumSize(new java.awt.Dimension(780, 466));
        body.setMinimumSize(new java.awt.Dimension(780, 466));
        body.setPreferredSize(new java.awt.Dimension(780, 466));

        userinfo.setMaximumSize(new java.awt.Dimension(370, 375));
        userinfo.setMinimumSize(new java.awt.Dimension(370, 375));
        userinfo.setPreferredSize(new java.awt.Dimension(370, 375));

        userinfoheader.setMaximumSize(new java.awt.Dimension(350, 50));
        userinfoheader.setMinimumSize(new java.awt.Dimension(350, 50));

        infotitle.setFont(new java.awt.Font("Arial", 2, 18)); // NOI18N
        infotitle.setText("User Information");
        infotitle.setMaximumSize(new java.awt.Dimension(150, 50));
        infotitle.setMinimumSize(new java.awt.Dimension(150, 50));
        infotitle.setPreferredSize(new java.awt.Dimension(150, 50));

        javax.swing.GroupLayout userinfoheaderLayout = new javax.swing.GroupLayout(userinfoheader);
        userinfoheader.setLayout(userinfoheaderLayout);
        userinfoheaderLayout.setHorizontalGroup(
            userinfoheaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userinfoheaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(infotitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(190, Short.MAX_VALUE))
        );
        userinfoheaderLayout.setVerticalGroup(
            userinfoheaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(infotitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        userinfodata.setMaximumSize(new java.awt.Dimension(350, 308));
        userinfodata.setMinimumSize(new java.awt.Dimension(350, 308));

        basicinfo.setMaximumSize(new java.awt.Dimension(350, 78));
        basicinfo.setMinimumSize(new java.awt.Dimension(350, 78));
        basicinfo.setPreferredSize(new java.awt.Dimension(350, 78));

        firstname.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        firstname.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        firstname.setText("First Name:");
        firstname.setMaximumSize(new java.awt.Dimension(75, 25));
        firstname.setMinimumSize(new java.awt.Dimension(75, 25));
        firstname.setPreferredSize(new java.awt.Dimension(75, 25));

        fnmfield.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        fnmfield.setToolTipText("User's given name");
        fnmfield.setMaximumSize(new java.awt.Dimension(235, 25));
        fnmfield.setMinimumSize(new java.awt.Dimension(235, 25));
        fnmfield.setPreferredSize(new java.awt.Dimension(235, 25));

        lastname.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lastname.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lastname.setText("Last Name:");
        lastname.setMaximumSize(new java.awt.Dimension(75, 25));
        lastname.setMinimumSize(new java.awt.Dimension(75, 25));
        lastname.setPreferredSize(new java.awt.Dimension(75, 25));

        lnmfield.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lnmfield.setToolTipText("User's surname");
        lnmfield.setMaximumSize(new java.awt.Dimension(235, 25));
        lnmfield.setMinimumSize(new java.awt.Dimension(235, 25));
        lnmfield.setPreferredSize(new java.awt.Dimension(235, 25));

        javax.swing.GroupLayout basicinfoLayout = new javax.swing.GroupLayout(basicinfo);
        basicinfo.setLayout(basicinfoLayout);
        basicinfoLayout.setHorizontalGroup(
            basicinfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, basicinfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(basicinfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(basicinfoLayout.createSequentialGroup()
                        .addComponent(firstname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(fnmfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(basicinfoLayout.createSequentialGroup()
                        .addComponent(lastname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lnmfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        basicinfoLayout.setVerticalGroup(
            basicinfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(basicinfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(basicinfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fnmfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(basicinfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lastname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lnmfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        firstname.getAccessibleContext().setAccessibleName("First Name");

        advinfo.setMaximumSize(new java.awt.Dimension(350, 140));
        advinfo.setMinimumSize(new java.awt.Dimension(350, 140));
        advinfo.setPreferredSize(new java.awt.Dimension(350, 140));

        username.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        username.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        username.setText("Username:");
        username.setMaximumSize(new java.awt.Dimension(75, 25));
        username.setMinimumSize(new java.awt.Dimension(75, 25));
        username.setPreferredSize(new java.awt.Dimension(75, 25));

        unmfield.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        unmfield.setToolTipText("Requested username. Username can be no longer than 10 characters in length.");
        unmfield.setMaximumSize(new java.awt.Dimension(235, 25));
        unmfield.setMinimumSize(new java.awt.Dimension(235, 25));
        unmfield.setPreferredSize(new java.awt.Dimension(235, 25));

        passwd.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        passwd.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        passwd.setText("Password:");
        passwd.setMaximumSize(new java.awt.Dimension(75, 25));
        passwd.setMinimumSize(new java.awt.Dimension(75, 25));
        passwd.setPreferredSize(new java.awt.Dimension(75, 25));

        pwdfield.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        pwdfield.setToolTipText("Enter the user's password.");
        pwdfield.setMaximumSize(new java.awt.Dimension(235, 25));
        pwdfield.setMinimumSize(new java.awt.Dimension(235, 25));
        pwdfield.setPreferredSize(new java.awt.Dimension(235, 25));
        pwdfield.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pwdfieldFocusGained(evt);
            }
        });

        cpasswd.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        cpasswd.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        cpasswd.setText("Confirm:");
        cpasswd.setMaximumSize(new java.awt.Dimension(75, 25));
        cpasswd.setMinimumSize(new java.awt.Dimension(75, 25));
        cpasswd.setPreferredSize(new java.awt.Dimension(75, 25));

        cpwdfield.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        cpwdfield.setToolTipText("Re-enter the user's password");
        cpwdfield.setMaximumSize(new java.awt.Dimension(235, 25));
        cpwdfield.setMinimumSize(new java.awt.Dimension(235, 25));
        cpwdfield.setPreferredSize(new java.awt.Dimension(235, 25));
        cpwdfield.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cpwdfieldFocusGained(evt);
            }
        });

        email.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        email.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        email.setText("Email:");
        email.setMaximumSize(new java.awt.Dimension(75, 25));
        email.setMinimumSize(new java.awt.Dimension(75, 25));
        email.setPreferredSize(new java.awt.Dimension(75, 25));

        emlfield.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        emlfield.setText("Email Address");
        emlfield.setToolTipText("Enter the user's email address.");
        emlfield.setMaximumSize(new java.awt.Dimension(235, 25));
        emlfield.setMinimumSize(new java.awt.Dimension(235, 25));
        emlfield.setPreferredSize(new java.awt.Dimension(235, 25));
        emlfield.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                emlfieldFocusGained(evt);
            }
        });

        javax.swing.GroupLayout advinfoLayout = new javax.swing.GroupLayout(advinfo);
        advinfo.setLayout(advinfoLayout);
        advinfoLayout.setHorizontalGroup(
            advinfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(advinfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(advinfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(advinfoLayout.createSequentialGroup()
                        .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(unmfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(advinfoLayout.createSequentialGroup()
                        .addComponent(passwd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pwdfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(advinfoLayout.createSequentialGroup()
                        .addComponent(cpasswd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cpwdfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(advinfoLayout.createSequentialGroup()
                        .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(emlfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        advinfoLayout.setVerticalGroup(
            advinfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(advinfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(advinfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(unmfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(advinfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pwdfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(advinfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cpasswd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cpwdfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(advinfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emlfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        othinfo.setMaximumSize(new java.awt.Dimension(350, 78));
        othinfo.setMinimumSize(new java.awt.Dimension(350, 78));
        othinfo.setPreferredSize(new java.awt.Dimension(350, 78));

        teamlabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        teamlabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        teamlabel.setText("Dev Team:");
        teamlabel.setMaximumSize(new java.awt.Dimension(75, 25));
        teamlabel.setMinimumSize(new java.awt.Dimension(75, 25));
        teamlabel.setPreferredSize(new java.awt.Dimension(75, 25));

        otherinfo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        otherinfo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DEV-SCM", "Information Technology", "Legal Team", "Super User", "Other" }));
        otherinfo.setMaximumSize(new java.awt.Dimension(235, 25));
        otherinfo.setMinimumSize(new java.awt.Dimension(235, 25));
        otherinfo.setPreferredSize(new java.awt.Dimension(235, 25));

        clrusrdata.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        clrusrdata.setText("Clear User Info Fields");
        clrusrdata.setMaximumSize(new java.awt.Dimension(160, 25));
        clrusrdata.setMinimumSize(new java.awt.Dimension(160, 25));
        clrusrdata.setPreferredSize(new java.awt.Dimension(160, 25));
        clrusrdata.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clrusrdataMouseClicked(evt);
            }
        });

        chkpassword.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        chkpassword.setText("Check Password");
        chkpassword.setMaximumSize(new java.awt.Dimension(160, 25));
        chkpassword.setMinimumSize(new java.awt.Dimension(160, 25));
        chkpassword.setPreferredSize(new java.awt.Dimension(160, 25));
        chkpassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                chkpasswordMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout othinfoLayout = new javax.swing.GroupLayout(othinfo);
        othinfo.setLayout(othinfoLayout);
        othinfoLayout.setHorizontalGroup(
            othinfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(othinfoLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(othinfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(othinfoLayout.createSequentialGroup()
                        .addComponent(chkpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(clrusrdata, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(othinfoLayout.createSequentialGroup()
                        .addComponent(teamlabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(otherinfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        othinfoLayout.setVerticalGroup(
            othinfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, othinfoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(othinfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(teamlabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(otherinfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(othinfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clrusrdata, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chkpassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6))
        );

        javax.swing.GroupLayout userinfodataLayout = new javax.swing.GroupLayout(userinfodata);
        userinfodata.setLayout(userinfodataLayout);
        userinfodataLayout.setHorizontalGroup(
            userinfodataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userinfodataLayout.createSequentialGroup()
                .addGroup(userinfodataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(othinfo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(basicinfo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(advinfo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        userinfodataLayout.setVerticalGroup(
            userinfodataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userinfodataLayout.createSequentialGroup()
                .addComponent(basicinfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(advinfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(othinfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout userinfoLayout = new javax.swing.GroupLayout(userinfo);
        userinfo.setLayout(userinfoLayout);
        userinfoLayout.setHorizontalGroup(
            userinfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userinfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(userinfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(userinfodata, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userinfoheader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        userinfoLayout.setVerticalGroup(
            userinfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userinfoLayout.createSequentialGroup()
                .addComponent(userinfoheader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(userinfodata, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jSeparator3.setBackground(new java.awt.Color(229, 234, 237));
        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator3.setMaximumSize(new java.awt.Dimension(50, 10));

        userperm.setMaximumSize(new java.awt.Dimension(360, 375));
        userperm.setMinimumSize(new java.awt.Dimension(360, 375));
        userperm.setPreferredSize(new java.awt.Dimension(360, 375));

        permheader.setMaximumSize(new java.awt.Dimension(340, 50));
        permheader.setMinimumSize(new java.awt.Dimension(340, 50));
        permheader.setPreferredSize(new java.awt.Dimension(340, 50));

        permtitle.setFont(new java.awt.Font("Arial", 2, 18)); // NOI18N
        permtitle.setText("User Permissions");
        permtitle.setMaximumSize(new java.awt.Dimension(180, 50));
        permtitle.setMinimumSize(new java.awt.Dimension(180, 50));
        permtitle.setPreferredSize(new java.awt.Dimension(180, 50));

        javax.swing.GroupLayout permheaderLayout = new javax.swing.GroupLayout(permheader);
        permheader.setLayout(permheaderLayout);
        permheaderLayout.setHorizontalGroup(
            permheaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(permheaderLayout.createSequentialGroup()
                .addComponent(permtitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        permheaderLayout.setVerticalGroup(
            permheaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(permtitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        permdata.setMaximumSize(new java.awt.Dimension(340, 319));
        permdata.setMinimumSize(new java.awt.Dimension(340, 319));
        permdata.setPreferredSize(new java.awt.Dimension(340, 319));

        usrstatlabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        usrstatlabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        usrstatlabel.setText("User Status");
        usrstatlabel.setMaximumSize(new java.awt.Dimension(94, 25));
        usrstatlabel.setMinimumSize(new java.awt.Dimension(94, 25));
        usrstatlabel.setPreferredSize(new java.awt.Dimension(94, 25));

        userstatus.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        userstatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Disabled", "Active", "Mark for Delete", "Super User" }));
        userstatus.setSelectedIndex(1);
        userstatus.setToolTipText("Select the status of the user account");
        userstatus.setMaximumSize(new java.awt.Dimension(145, 25));
        userstatus.setMinimumSize(new java.awt.Dimension(145, 25));
        userstatus.setPreferredSize(new java.awt.Dimension(145, 25));

        actflglabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        actflglabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        actflglabel.setText("Account Flags");
        actflglabel.setMaximumSize(new java.awt.Dimension(94, 25));
        actflglabel.setMinimumSize(new java.awt.Dimension(94, 25));
        actflglabel.setPreferredSize(new java.awt.Dimension(94, 25));

        acctflags.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        acctflags.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Account Locked", "Contact Sysadmin", "Expire Password", "Super User", "Normal Use" }));
        acctflags.setSelectedIndex(4);
        acctflags.setMaximumSize(new java.awt.Dimension(145, 25));
        acctflags.setMinimumSize(new java.awt.Dimension(145, 25));
        acctflags.setPreferredSize(new java.awt.Dimension(145, 25));

        jSeparator4.setMaximumSize(new java.awt.Dimension(320, 5));
        jSeparator4.setMinimumSize(new java.awt.Dimension(320, 5));
        jSeparator4.setPreferredSize(new java.awt.Dimension(320, 5));

        prmdatalabel.setFont(new java.awt.Font("Arial", 2, 12)); // NOI18N
        prmdatalabel.setText("Permission Selection");
        prmdatalabel.setMaximumSize(new java.awt.Dimension(125, 25));
        prmdatalabel.setMinimumSize(new java.awt.Dimension(125, 25));
        prmdatalabel.setPreferredSize(new java.awt.Dimension(125, 25));

        permlist.setBackground(new java.awt.Color(255, 255, 255));
        permlist.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        permlist.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        permlist.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        permlist.setMaximumSize(new java.awt.Dimension(180, 185));
        permlist.setMinimumSize(new java.awt.Dimension(180, 175));
        permlist.setPreferredSize(new java.awt.Dimension(180, 183));

        permissionlist.setBackground(new java.awt.Color(240, 240, 240));
        permissionlist.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        permissionlist.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Login/Read-Only", "Reporting Only", "Audit Only", "Reporting & Audit", "Escrow Only", "Escrow & Reporting", "Escrow & Audit", "Escrow, Audit & Reporting", "User Modification", "All Functions", " " };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        permissionlist.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        permissionlist.setAutoscrolls(false);
        permissionlist.setMaximumSize(new java.awt.Dimension(180, 183));
        permissionlist.setMinimumSize(new java.awt.Dimension(180, 183));
        permissionlist.setOpaque(false);
        permissionlist.setPreferredSize(new java.awt.Dimension(180, 183));
        permissionlist.setSelectedIndex(0);
        permissionlist.setVisibleRowCount(10);
        permlist.setViewportView(permissionlist);

        permdisplay.setEditable(false);
        permdisplay.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        permdisplay.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        permdisplay.setText("Decoded String");
        permdisplay.setToolTipText("Displays permission string");
        permdisplay.setMaximumSize(new java.awt.Dimension(125, 30));
        permdisplay.setMinimumSize(new java.awt.Dimension(125, 30));
        permdisplay.setPreferredSize(new java.awt.Dimension(125, 30));

        permpreview.setFont(new java.awt.Font("Arial", 2, 12)); // NOI18N
        permpreview.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        permpreview.setText("Permissions Preview");
        permpreview.setMaximumSize(new java.awt.Dimension(125, 30));
        permpreview.setMinimumSize(new java.awt.Dimension(125, 30));
        permpreview.setPreferredSize(new java.awt.Dimension(125, 30));

        permview.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        permview.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        permview.setMaximumSize(new java.awt.Dimension(125, 88));
        permview.setMinimumSize(new java.awt.Dimension(125, 88));
        permview.setPreferredSize(new java.awt.Dimension(125, 88));

        encodedperm.setEditable(false);
        encodedperm.setBackground(new java.awt.Color(240, 240, 240));
        encodedperm.setColumns(20);
        encodedperm.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        encodedperm.setLineWrap(true);
        encodedperm.setRows(5);
        encodedperm.setText("Encoded String");
        encodedperm.setToolTipText("Shows the encoded value of the user permissions");
        encodedperm.setMargin(new java.awt.Insets(1, 1, 1, 1));
        encodedperm.setMaximumSize(new java.awt.Dimension(125, 88));
        encodedperm.setMinimumSize(new java.awt.Dimension(125, 88));
        encodedperm.setPreferredSize(new java.awt.Dimension(125, 88));
        permview.setViewportView(encodedperm);

        javax.swing.GroupLayout permdataLayout = new javax.swing.GroupLayout(permdata);
        permdata.setLayout(permdataLayout);
        permdataLayout.setHorizontalGroup(
            permdataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(permdataLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(permdataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(prmdatalabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(permdataLayout.createSequentialGroup()
                        .addGroup(permdataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(actflglabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(usrstatlabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(permdataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(userstatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(acctflags, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jSeparator4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(permdataLayout.createSequentialGroup()
                        .addComponent(permlist, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(permdataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(permdisplay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(permpreview, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(permview, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        permdataLayout.setVerticalGroup(
            permdataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(permdataLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(permdataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(usrstatlabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userstatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(permdataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(acctflags, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(actflglabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(prmdatalabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(permdataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(permdataLayout.createSequentialGroup()
                        .addComponent(permpreview, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(permdisplay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(permview, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(permlist, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout userpermLayout = new javax.swing.GroupLayout(userperm);
        userperm.setLayout(userpermLayout);
        userpermLayout.setHorizontalGroup(
            userpermLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, userpermLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(userpermLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(permdata, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(permheader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        userpermLayout.setVerticalGroup(
            userpermLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userpermLayout.createSequentialGroup()
                .addComponent(permheader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(permdata, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        btnpanel.setMaximumSize(new java.awt.Dimension(764, 76));
        btnpanel.setMinimumSize(new java.awt.Dimension(764, 76));
        btnpanel.setPreferredSize(new java.awt.Dimension(764, 76));

        inputvalidate.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        inputvalidate.setText("Validate Input(s)");
        inputvalidate.setMaximumSize(new java.awt.Dimension(160, 25));
        inputvalidate.setMinimumSize(new java.awt.Dimension(160, 25));
        inputvalidate.setPreferredSize(new java.awt.Dimension(160, 25));
        inputvalidate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                inputvalidateMouseClicked(evt);
            }
        });

        returntomain.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        returntomain.setText("Return to Main Menu");
        returntomain.setMaximumSize(new java.awt.Dimension(160, 25));
        returntomain.setMinimumSize(new java.awt.Dimension(160, 25));
        returntomain.setPreferredSize(new java.awt.Dimension(160, 25));
        returntomain.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                returntomainMouseClicked(evt);
            }
        });

        submitinfo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        submitinfo.setText("Submit Information");
        submitinfo.setEnabled(false);
        submitinfo.setMaximumSize(new java.awt.Dimension(160, 25));
        submitinfo.setMinimumSize(new java.awt.Dimension(160, 25));
        submitinfo.setPreferredSize(new java.awt.Dimension(160, 25));
        submitinfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                submitinfoMouseClicked(evt);
            }
        });

        previewprm.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        previewprm.setText("Preview Permissions");
        previewprm.setMaximumSize(new java.awt.Dimension(160, 25));
        previewprm.setMinimumSize(new java.awt.Dimension(160, 25));
        previewprm.setPreferredSize(new java.awt.Dimension(160, 25));
        previewprm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                previewprmMouseClicked(evt);
            }
        });

        clrprmdata.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        clrprmdata.setText("Clear Permissions");
        clrprmdata.setMaximumSize(new java.awt.Dimension(160, 25));
        clrprmdata.setMinimumSize(new java.awt.Dimension(160, 25));
        clrprmdata.setPreferredSize(new java.awt.Dimension(160, 25));
        clrprmdata.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clrprmdataMouseClicked(evt);
            }
        });

        usrprmhelp.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        usrprmhelp.setText("Help");
        usrprmhelp.setMaximumSize(new java.awt.Dimension(100, 25));
        usrprmhelp.setMinimumSize(new java.awt.Dimension(100, 25));
        usrprmhelp.setPreferredSize(new java.awt.Dimension(100, 25));

        javax.swing.GroupLayout btnpanelLayout = new javax.swing.GroupLayout(btnpanel);
        btnpanel.setLayout(btnpanelLayout);
        btnpanelLayout.setHorizontalGroup(
            btnpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnpanelLayout.createSequentialGroup()
                .addGroup(btnpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(btnpanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(returntomain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(btnpanelLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(usrprmhelp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 144, Short.MAX_VALUE)
                .addGroup(btnpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(btnpanelLayout.createSequentialGroup()
                        .addComponent(submitinfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 120, Short.MAX_VALUE)
                        .addComponent(clrprmdata, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(btnpanelLayout.createSequentialGroup()
                        .addComponent(inputvalidate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(previewprm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        btnpanelLayout.setVerticalGroup(
            btnpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnpanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(btnpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputvalidate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(returntomain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(previewprm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(btnpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usrprmhelp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(submitinfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clrprmdata, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout bodyLayout = new javax.swing.GroupLayout(body);
        body.setLayout(bodyLayout);
        bodyLayout.setHorizontalGroup(
            bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bodyLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(bodyLayout.createSequentialGroup()
                        .addComponent(userinfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(userperm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        bodyLayout.setVerticalGroup(
            bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bodyLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(userperm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(userinfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        footer.setBackground(new java.awt.Color(229, 234, 237));
        footer.setMaximumSize(new java.awt.Dimension(800, 36));
        footer.setMinimumSize(new java.awt.Dimension(800, 36));
        footer.setName(""); // NOI18N
        footer.setPreferredSize(new java.awt.Dimension(800, 36));

        userstatusBar.setBackground(new java.awt.Color(229, 234, 237));
        userstatusBar.setBorder(null);
        userstatusBar.setFloatable(false);
        userstatusBar.setRollover(true);
        userstatusBar.setMaximumSize(new java.awt.Dimension(800, 36));
        userstatusBar.setMinimumSize(new java.awt.Dimension(800, 36));
        userstatusBar.setPreferredSize(new java.awt.Dimension(800, 36));

        LocalDate date = LocalDate.now();
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("MM/dd/yyy");
        statbarDate.setText(" System Date: "+date.format(dtf));
        statbarDate.setBackground(new java.awt.Color(229, 234, 237));
        statbarDate.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        userstatusBar.add(statbarDate);
        userstatusBar.add(jSeparator1);

        int delay = 10;
        ActionListener taskPerformer = new ActionListener(){
            public void actionPerformed(ActionEvent evt){
                String sysTime = new java.text.SimpleDateFormat("HH:mm:ss").format(new java.util.Date(System.currentTimeMillis()));
                statbarTime.setText(" System Time: "+sysTime);
            }
        };
        new Timer(delay, taskPerformer).start();
        statbarTime.setBackground(new java.awt.Color(229, 234, 237));
        statbarTime.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        userstatusBar.add(statbarTime);
        userstatusBar.add(jSeparator2);

        dispUsername.setBackground(new java.awt.Color(229, 234, 237));
        dispUsername.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        dispUsername.setText("<Username_Placeholder>");
        userstatusBar.add(dispUsername);

        javax.swing.GroupLayout footerLayout = new javax.swing.GroupLayout(footer);
        footer.setLayout(footerLayout);
        footerLayout.setHorizontalGroup(
            footerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(userstatusBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        footerLayout.setVerticalGroup(
            footerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, footerLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(userstatusBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout innercontentLayout = new javax.swing.GroupLayout(innercontent);
        innercontent.setLayout(innercontentLayout);
        innercontentLayout.setHorizontalGroup(
            innercontentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(innercontentLayout.createSequentialGroup()
                .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(innercontentLayout.createSequentialGroup()
                .addGroup(innercontentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(innercontentLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(footer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(innercontentLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(body, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        innercontentLayout.setVerticalGroup(
            innercontentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, innercontentLayout.createSequentialGroup()
                .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(body, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(footer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(innercontent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(innercontent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pwdfieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pwdfieldFocusGained
        pwdfield.setText("");
    }//GEN-LAST:event_pwdfieldFocusGained

    private void cpwdfieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cpwdfieldFocusGained
        cpwdfield.setText("");
    }//GEN-LAST:event_cpwdfieldFocusGained

    private void emlfieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emlfieldFocusGained
        emlfield.setText("");
    }//GEN-LAST:event_emlfieldFocusGained

    private void previewprmMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_previewprmMouseClicked
        //Instantiates three integer variables to hold the selection info
        int asi = userstatus.getSelectedIndex();
        int ean = acctflags.getSelectedIndex();
        int osi = otherinfo.getSelectedIndex();
        int perms = permissionlist.getSelectedIndex();
        
        //Initialize ACL Calculator & ACL Encoder
        UserPermissions CalculateACL = new UserPermissions();
        EncodePermissions encoder = new EncodePermissions();
        
        //Load Account Status information and retrieve info to string
        
        CalculateACL.loadAccountStatusToTable();
        TreeMap<String,String> status = CalculateACL.getAcctStatusMap();
        String usrval = status.get(String.valueOf(asi));
        
        //Load Account Flag information
        CalculateACL.loadAccountFlagsToTable();
        TreeMap<String,String> flags = CalculateACL.getAcctFlagsMap();
        String usrflags = flags.get(String.valueOf(ean));
        
        //Load Account Details info
        CalculateACL.loadAccountInformationToTable();
        TreeMap<String,String> info = CalculateACL.getAcctInfoMap();
        String usrinfo = info.get(String.valueOf(osi));
        
        //Load Account Permission info
        CalculateACL.loadAccountControlsToTable();
        TreeMap<String,String> pctrl = CalculateACL.getAcctCtrlMap();
        String permctrl = pctrl.get(String.valueOf(perms));
        
        //Declare Encoder variables and assign a null value
        String permissions = null;
        //String decString = null;
        String hexString = null;
        
        //Construct permission string
        permissions = String.format(usrval+"-"+permctrl+"-"+usrflags+"-"+usrinfo);
        
        //Encode Permissions
        encoder.encodePermissionData(permissions);
        hexString = encoder.returnEncodedPermissions();
        
        //Print Decoded and Encoded Permission String to Preview Pane
        permdisplay.setText(usrval+"-"+permctrl+"-"+usrflags+"-"+usrinfo);
        encodedperm.setText(hexString);
        
        /*
        FOR TESTING ONLY: Decode permissions and compare strings
        encoder.decodePermissionData(hexString);
        decString = encoder.returnDecodedPermissions();
        encoder.comparePermissionData(permissions, decString);
        String permCheck = encoder.getComparisonData();
        System.out.println(permCheck);
        */
    }//GEN-LAST:event_previewprmMouseClicked

    private void clrprmdataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clrprmdataMouseClicked
        permdisplay.setText("");
        encodedperm.setText("");
        permissionlist.setSelectedIndex(0);
        userstatus.setSelectedIndex(1);
        acctflags.setSelectedIndex(4);
        otherinfo.setSelectedIndex(0);
    }//GEN-LAST:event_clrprmdataMouseClicked

    private void clrusrdataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clrusrdataMouseClicked
        fnmfield.setText("");
        fnmfield.setBackground(Color.WHITE);
        lnmfield.setText("");
        lnmfield.setBackground(Color.WHITE);
        emlfield.setText("");
        emlfield.setBackground(Color.WHITE);
        unmfield.setText("");
        unmfield.setBackground(Color.WHITE);
        pwdfield.setText("");
        pwdfield.setBackground(Color.WHITE);
        cpwdfield.setText("");
        cpwdfield.setBackground(Color.WHITE);
        submitinfo.setEnabled(false);
    }//GEN-LAST:event_clrusrdataMouseClicked

    private void returntomainMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_returntomainMouseClicked
        //Un-hide the Main Menu Frame.
        JFrame opsmm;
        opsmm = new OperationsMenu();
        opsmm.setLocationRelativeTo(null);
        opsmm.setVisible(true);
        opsmm.pack();
        this.dispose();
    }//GEN-LAST:event_returntomainMouseClicked

    private void inputvalidateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inputvalidateMouseClicked
        //Initialize validator instance
        InputValidation UserValidation = new InputValidation();
        
        //Validate the first and last name fields
        new Thread(() -> {
            String fnm = fnmfield.getText();
            String lnm = lnmfield.getText();
            javax.swing.JTextField firstname = fnmfield;
            javax.swing.JTextField lastname = lnmfield;
            UserValidation.validateUserIdentification(fnm, lnm, firstname, lastname);
        }).start();
        
        
        //Validate username and email address
        new Thread(() -> {
            String username = unmfield.getText();
            String email = emlfield.getText();
            javax.swing.JTextField usernamefield = unmfield;
            javax.swing.JTextField emailfield = emlfield;
            UserValidation.validateUserID(username, usernamefield);
            UserValidation.validateEmailAddress(email, emailfield);     
        }).start();
   
        //Validate Super User selections only if a superuser option is selected
        new Thread(() -> {
            int usrstat = userstatus.getSelectedIndex();
            int usrctrl = permissionlist.getSelectedIndex();
            int usrflags = acctflags.getSelectedIndex();
            int usrinfo = otherinfo.getSelectedIndex();
            if((usrstat == 3) || (usrctrl == 9) || (usrflags == 3) || (usrinfo == 3)){
                new Thread(() ->{
                    javax.swing.JButton subinfo = submitinfo;
                    javax.swing.JComboBox status = userstatus;
                    javax.swing.JComboBox flags = acctflags;
                    javax.swing.JComboBox info = otherinfo;
                    javax.swing.JList ctrl = permissionlist;
                    UserValidation.validateSuperUserPermissions(usrstat, usrctrl, usrflags, usrinfo, subinfo, status, ctrl, flags, info);
                    UserValidation.validationComplete();
                    submitinfo.setEnabled(true);
                }).start();   
            }else{
                UserValidation.validationComplete();
                submitinfo.setEnabled(true);
            }
        }).start();
       
    }//GEN-LAST:event_inputvalidateMouseClicked

    private void submitinfoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submitinfoMouseClicked
        //Variable Declaration
	int acctstat = userstatus.getSelectedIndex();
	int permselect = permissionlist.getSelectedIndex();
	int acctflag = acctflags.getSelectedIndex();
	int othinfo = otherinfo.getSelectedIndex();
	String fnm = fnmfield.getText();
	String lnm = lnmfield.getText();
	String unm = unmfield.getText();
	String email = emlfield.getText();
        String address = emlfield.getText();
	String password = String.valueOf(pwdfield.getPassword());
        String permissions;
	String bcryptHashString;
	String hexString = null;
	String decString = null;
	Boolean permCheck = null;
	Boolean pwdCheck = null;

	//Initialize the Permission calculator, Permission Encoder and Password Encrypter
	UserPermissions calculator = new UserPermissions();
	EncodePermissions encoder = new EncodePermissions();
	EncryptPassword encryption = new EncryptPassword();

	//Calculate permission string segments
	calculator.loadAccountStatusToTable();
	TreeMap<String,String> status = calculator.getAcctStatusMap();
	String usrval = status.get(String.valueOf(acctstat));

	calculator.loadAccountControlsToTable();
	TreeMap<String,String> pctrl = calculator.getAcctCtrlMap();
	String permctrl = pctrl.get(String.valueOf(permselect));
		   
	calculator.loadAccountFlagsToTable();
	TreeMap<String,String> flags = calculator.getAcctFlagsMap();
	String usrflags = flags.get(String.valueOf(acctflag));
				
	calculator.loadAccountInformationToTable();
	TreeMap<String,String> info = calculator.getAcctInfoMap();
	String usrinfo = info.get(String.valueOf(othinfo));

	//Concatenate the segments into a cohesive string and encode for storage
	permissions = String.format(usrval+"-"+permctrl+"-"+usrflags+"-"+usrinfo);
	encoder.encodePermissionData(permissions);
	hexString = encoder.returnEncodedPermissions();

	//Validate coded permissions and unencoded permissions are equal
	encoder.decodePermissionData(hexString);
	decString = encoder.returnDecodedPermissions();
        encoder.comparePermissionData(permissions, decString);
        permCheck = encoder.getComparisonData();   
        
        //Encrypt and verify user password
        encryption.hashPassword(password);
        bcryptHashString = encryption.getBCryptHashString();
        encryption.verifyPassword(bcryptHashString, password);
        pwdCheck = encryption.getVerificationStatus();
        
        //Commit Information to Database
        DatabaseOperations useradd = new DatabaseOperations();
        useradd.commitUserInfo(fnm, lnm, unm, email, bcryptHashString, hexString);
        
        //Send email to user with account information
        MailerSubsystem sendmail = new MailerSubsystem();
        sendmail.sendAcctDetailsOnCreation(fnm, lnm, address, unm, password);
        
    }//GEN-LAST:event_submitinfoMouseClicked

    private void chkpasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chkpasswordMouseClicked
        String passwd = String.valueOf(pwdfield.getPassword());
        String passconf = String.valueOf(cpwdfield.getPassword());
        javax.swing.JPasswordField passfield = pwdfield;
        javax.swing.JPasswordField pwdconf = cpwdfield;
        new Thread(() -> {
            InputValidation checker = new InputValidation();
            checker.validateUserPassword(passwd, passconf, passfield, pwdconf);
        }).start();       
    }//GEN-LAST:event_chkpasswordMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> acctflags;
    private javax.swing.JLabel actflglabel;
    private javax.swing.JPanel advinfo;
    private javax.swing.JPanel basicinfo;
    private javax.swing.JPanel body;
    private javax.swing.JPanel btnpanel;
    private javax.swing.JButton chkpassword;
    private javax.swing.JButton clrprmdata;
    private javax.swing.JButton clrusrdata;
    private javax.swing.JLabel cpasswd;
    private javax.swing.JPasswordField cpwdfield;
    private javax.swing.JLabel dispUsername;
    private javax.swing.JLabel email;
    private javax.swing.JTextField emlfield;
    private javax.swing.JTextArea encodedperm;
    private javax.swing.JLabel firstname;
    private javax.swing.JTextField fnmfield;
    private javax.swing.JPanel footer;
    private javax.swing.JPanel header;
    private javax.swing.JLabel idslogo;
    private javax.swing.JLabel infotitle;
    private javax.swing.JPanel innercontent;
    private javax.swing.JButton inputvalidate;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel lastname;
    private javax.swing.JTextField lnmfield;
    private javax.swing.JComboBox<String> otherinfo;
    private javax.swing.JPanel othinfo;
    private javax.swing.JLabel pagetitle;
    private javax.swing.JLabel passwd;
    private javax.swing.JPanel permdata;
    private javax.swing.JTextField permdisplay;
    private javax.swing.JPanel permheader;
    private javax.swing.JList<String> permissionlist;
    private javax.swing.JScrollPane permlist;
    private javax.swing.JLabel permpreview;
    private javax.swing.JLabel permtitle;
    private javax.swing.JScrollPane permview;
    private javax.swing.JButton previewprm;
    private javax.swing.JLabel prmdatalabel;
    private javax.swing.JPasswordField pwdfield;
    private javax.swing.JButton returntomain;
    private javax.swing.JLabel statbarDate;
    private javax.swing.JLabel statbarTime;
    private javax.swing.JButton submitinfo;
    private javax.swing.JLabel teamlabel;
    private javax.swing.JTextField unmfield;
    private javax.swing.JPanel userinfo;
    private javax.swing.JPanel userinfodata;
    private javax.swing.JPanel userinfoheader;
    private javax.swing.JLabel username;
    private javax.swing.JPanel userperm;
    private javax.swing.JComboBox<String> userstatus;
    private javax.swing.JToolBar userstatusBar;
    private javax.swing.JButton usrprmhelp;
    private javax.swing.JLabel usrstatlabel;
    // End of variables declaration//GEN-END:variables
}
