/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ids.ops.escrow.uix;

import com.ids.ops.escrow.uix.modules.AddUser;
import com.ids.ops.escrow.uix.modules.InfoLeaseOperations;
import com.ids.ops.escrow.security.login.UserLogin;
import com.ids.ops.escrow.security.validation.ValidateConnections;
import com.ids.ops.escrow.uix.modules.AddCustomer;
import com.ids.ops.escrow.uix.modules.BrowseCustomer;
import com.ids.ops.escrow.uix.modules.ModifyCustomer;
import com.jcraft.jsch.*;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.time.format.DateTimeFormatter;
import java.time.LocalDate;
import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Timer;
/**
 *
 * @author paul20
 */
public class OperationsMenu extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public OperationsMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        opsEncapsulation = new javax.swing.JPanel();
        opsHeader = new javax.swing.JPanel();
        idsLogo = new javax.swing.JLabel();
        appTitle = new javax.swing.JLabel();
        opsContent = new javax.swing.JPanel();
        opsEscrow = new javax.swing.JPanel();
        opsEscrowTitle = new javax.swing.JLabel();
        opsEscrowBtnMnu = new javax.swing.JPanel();
        btnLabelIL10 = new javax.swing.JLabel();
        escrowIL10 = new javax.swing.JButton();
        btnLabelIL9 = new javax.swing.JLabel();
        escrowIL9 = new javax.swing.JButton();
        btnLabelIAQE = new javax.swing.JLabel();
        escrowIAQE = new javax.swing.JButton();
        btnLabelRapport = new javax.swing.JLabel();
        escrowRapport = new javax.swing.JButton();
        btnLabelLegacy = new javax.swing.JLabel();
        escrowLegacy = new javax.swing.JButton();
        btnLabelAllProd = new javax.swing.JLabel();
        escrowAllProducts = new javax.swing.JButton();
        escrowHelpBtn = new javax.swing.JButton();
        opsReporting = new javax.swing.JPanel();
        opsReportingTitle = new javax.swing.JLabel();
        opsReportingBtnMnu = new javax.swing.JPanel();
        reportsAuditLabel = new javax.swing.JLabel();
        reportsAudit = new javax.swing.JButton();
        reportsCustomerLabel = new javax.swing.JLabel();
        customerOps = new javax.swing.JButton();
        reportsEscrowLabel = new javax.swing.JLabel();
        reportsEscrow = new javax.swing.JButton();
        reportsUserLabel = new javax.swing.JLabel();
        reportsUser = new javax.swing.JButton();
        reportsHelpBtn = new javax.swing.JButton();
        opsGlobalUser = new javax.swing.JPanel();
        opsGlobalUsersTitle = new javax.swing.JLabel();
        opsGlobalUserBtnMnu = new javax.swing.JPanel();
        glbusersAddLabel = new javax.swing.JLabel();
        glbusersAdd = new javax.swing.JButton();
        glbusersModifyLabel = new javax.swing.JLabel();
        glbusersModify = new javax.swing.JButton();
        glbusersCleanLabel = new javax.swing.JLabel();
        glbusersClean = new javax.swing.JButton();
        opsUser = new javax.swing.JPanel();
        opsUsersTitle = new javax.swing.JLabel();
        opsUserBtnMnu = new javax.swing.JPanel();
        userChangePwd = new javax.swing.JButton();
        userChangePwd1 = new javax.swing.JButton();
        opsFooter = new javax.swing.JPanel();
        statusBar = new javax.swing.JToolBar();
        statbarDate = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        statbarTime = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        dispUsername = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        logoutButton = new javax.swing.JButton();
        opsMenu = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        changeCommit = new javax.swing.JMenuItem();
        fileSeparator = new javax.swing.JPopupMenu.Separator();
        menuLogout = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        jdbcTest = new javax.swing.JMenuItem();
        ftpTest = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        helpAbout = new javax.swing.JMenuItem();
        helpSeparator = new javax.swing.JPopupMenu.Separator();
        helpWebHelp = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("IDS Operations: Escrow - Main Menu");
        setBackground(new java.awt.Color(229, 234, 237));
        setMinimumSize(new java.awt.Dimension(1078, 623));
        setName("MainMenu"); // NOI18N
        setResizable(false);

        opsEncapsulation.setBackground(new java.awt.Color(229, 234, 237));
        opsEncapsulation.setMaximumSize(new java.awt.Dimension(1078, 567));
        opsEncapsulation.setMinimumSize(new java.awt.Dimension(1078, 567));

        opsHeader.setBackground(new java.awt.Color(229, 234, 237));
        opsHeader.setMaximumSize(new java.awt.Dimension(1078, 65));
        opsHeader.setMinimumSize(new java.awt.Dimension(1078, 65));
        opsHeader.setPreferredSize(new java.awt.Dimension(1078, 65));

        idsLogo.setBackground(new java.awt.Color(229, 234, 237));
        idsLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/IDSColor.jpg"))); // NOI18N
        idsLogo.setMaximumSize(new java.awt.Dimension(240, 65));
        idsLogo.setMinimumSize(new java.awt.Dimension(240, 65));
        idsLogo.setPreferredSize(new java.awt.Dimension(240, 65));

        appTitle.setBackground(new java.awt.Color(229, 234, 237));
        appTitle.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        appTitle.setForeground(new java.awt.Color(121, 123, 128));
        appTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        appTitle.setText("IDS Operations: Escrow");

        javax.swing.GroupLayout opsHeaderLayout = new javax.swing.GroupLayout(opsHeader);
        opsHeader.setLayout(opsHeaderLayout);
        opsHeaderLayout.setHorizontalGroup(
            opsHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, opsHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(appTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 774, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(idsLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        opsHeaderLayout.setVerticalGroup(
            opsHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(opsHeaderLayout.createSequentialGroup()
                .addGroup(opsHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(appTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(idsLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        opsContent.setBackground(new java.awt.Color(229, 234, 237));
        opsContent.setMaximumSize(new java.awt.Dimension(1078, 434));
        opsContent.setMinimumSize(new java.awt.Dimension(1078, 434));

        opsEscrow.setMaximumSize(new java.awt.Dimension(290, 432));
        opsEscrow.setMinimumSize(new java.awt.Dimension(290, 432));
        opsEscrow.setPreferredSize(new java.awt.Dimension(290, 432));

        opsEscrowTitle.setFont(new java.awt.Font("Arial", 2, 18)); // NOI18N
        opsEscrowTitle.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        opsEscrowTitle.setText("Escrow Operations");
        opsEscrowTitle.setMaximumSize(new java.awt.Dimension(270, 50));
        opsEscrowTitle.setMinimumSize(new java.awt.Dimension(270, 50));
        opsEscrowTitle.setPreferredSize(new java.awt.Dimension(270, 50));

        btnLabelIL10.setFont(new java.awt.Font("Arial", 2, 12)); // NOI18N
        btnLabelIL10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btnLabelIL10.setText("IL10 Operations Menu");

        escrowIL10.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        escrowIL10.setText("InfoLease 10");
        escrowIL10.setToolTipText("Escrow InfoLease 10");
        escrowIL10.setMaximumSize(new java.awt.Dimension(115, 25));
        escrowIL10.setMinimumSize(new java.awt.Dimension(115, 25));
        escrowIL10.setPreferredSize(new java.awt.Dimension(115, 25));
        escrowIL10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                escrowIL10MouseClicked(evt);
            }
        });

        btnLabelIL9.setFont(new java.awt.Font("Arial", 2, 12)); // NOI18N
        btnLabelIL9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btnLabelIL9.setText("IL9 Operations Menu");

        escrowIL9.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        escrowIL9.setText("InfoLease 9");
        escrowIL9.setToolTipText("Escrow InfoLease 9");
        escrowIL9.setEnabled(false);
        escrowIL9.setMaximumSize(new java.awt.Dimension(115, 25));
        escrowIL9.setMinimumSize(new java.awt.Dimension(115, 25));
        escrowIL9.setPreferredSize(new java.awt.Dimension(115, 25));

        btnLabelIAQE.setFont(new java.awt.Font("Arial", 2, 12)); // NOI18N
        btnLabelIAQE.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btnLabelIAQE.setText("IA Operations Menu");

        escrowIAQE.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        escrowIAQE.setText("InfoAnalysis");
        escrowIAQE.setToolTipText("Escrow InfoAnalysis");
        escrowIAQE.setEnabled(false);
        escrowIAQE.setMaximumSize(new java.awt.Dimension(115, 25));
        escrowIAQE.setMinimumSize(new java.awt.Dimension(115, 25));
        escrowIAQE.setPreferredSize(new java.awt.Dimension(115, 25));

        btnLabelRapport.setFont(new java.awt.Font("Arial", 2, 12)); // NOI18N
        btnLabelRapport.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btnLabelRapport.setText("Rap Operations Menu");

        escrowRapport.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        escrowRapport.setText("Rapport");
        escrowRapport.setToolTipText("Escrow Rapport");
        escrowRapport.setEnabled(false);
        escrowRapport.setMaximumSize(new java.awt.Dimension(115, 25));
        escrowRapport.setMinimumSize(new java.awt.Dimension(115, 25));
        escrowRapport.setPreferredSize(new java.awt.Dimension(115, 25));

        btnLabelLegacy.setFont(new java.awt.Font("Arial", 2, 12)); // NOI18N
        btnLabelLegacy.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btnLabelLegacy.setText("Other Operations Menu");

        escrowLegacy.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        escrowLegacy.setText("Other Legacy");
        escrowLegacy.setToolTipText("Escrow CustomerCare & UseTrack");
        escrowLegacy.setEnabled(false);
        escrowLegacy.setMaximumSize(new java.awt.Dimension(115, 25));
        escrowLegacy.setMinimumSize(new java.awt.Dimension(115, 25));
        escrowLegacy.setPreferredSize(new java.awt.Dimension(115, 25));

        btnLabelAllProd.setFont(new java.awt.Font("Arial", 2, 12)); // NOI18N
        btnLabelAllProd.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btnLabelAllProd.setText("All Products Menu");

        escrowAllProducts.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        escrowAllProducts.setText("All Products");
        escrowAllProducts.setToolTipText("Escrow All Products");
        escrowAllProducts.setEnabled(false);
        escrowAllProducts.setMaximumSize(new java.awt.Dimension(115, 25));
        escrowAllProducts.setMinimumSize(new java.awt.Dimension(115, 25));
        escrowAllProducts.setPreferredSize(new java.awt.Dimension(115, 25));

        escrowHelpBtn.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        escrowHelpBtn.setText("Help");
        escrowHelpBtn.setToolTipText("Opens Help");
        escrowHelpBtn.setMaximumSize(new java.awt.Dimension(115, 25));
        escrowHelpBtn.setMinimumSize(new java.awt.Dimension(115, 25));
        escrowHelpBtn.setPreferredSize(new java.awt.Dimension(115, 25));

        javax.swing.GroupLayout opsEscrowBtnMnuLayout = new javax.swing.GroupLayout(opsEscrowBtnMnu);
        opsEscrowBtnMnu.setLayout(opsEscrowBtnMnuLayout);
        opsEscrowBtnMnuLayout.setHorizontalGroup(
            opsEscrowBtnMnuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(opsEscrowBtnMnuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(opsEscrowBtnMnuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnLabelIL10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLabelIL9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLabelIAQE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLabelRapport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLabelLegacy, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLabelAllProd, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(opsEscrowBtnMnuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(escrowAllProducts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(escrowLegacy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(escrowRapport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(escrowIAQE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(escrowIL9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(escrowIL10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(opsEscrowBtnMnuLayout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(escrowHelpBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        opsEscrowBtnMnuLayout.setVerticalGroup(
            opsEscrowBtnMnuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(opsEscrowBtnMnuLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(opsEscrowBtnMnuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(escrowIL10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLabelIL10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(opsEscrowBtnMnuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(escrowIL9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLabelIL9, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(opsEscrowBtnMnuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(escrowIAQE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLabelIAQE, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(opsEscrowBtnMnuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(escrowRapport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLabelRapport, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(opsEscrowBtnMnuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(escrowLegacy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLabelLegacy, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(opsEscrowBtnMnuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(escrowAllProducts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLabelAllProd, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(escrowHelpBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout opsEscrowLayout = new javax.swing.GroupLayout(opsEscrow);
        opsEscrow.setLayout(opsEscrowLayout);
        opsEscrowLayout.setHorizontalGroup(
            opsEscrowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(opsEscrowLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(opsEscrowTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(opsEscrowLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(opsEscrowBtnMnu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        opsEscrowLayout.setVerticalGroup(
            opsEscrowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(opsEscrowLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(opsEscrowTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(opsEscrowBtnMnu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(19, 19, 19))
        );

        opsReporting.setMaximumSize(new java.awt.Dimension(290, 432));
        opsReporting.setMinimumSize(new java.awt.Dimension(290, 432));
        opsReporting.setPreferredSize(new java.awt.Dimension(290, 432));

        opsReportingTitle.setFont(new java.awt.Font("Arial", 2, 18)); // NOI18N
        opsReportingTitle.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        opsReportingTitle.setText("Accounts & Reporting Operations");
        opsReportingTitle.setMaximumSize(new java.awt.Dimension(270, 50));
        opsReportingTitle.setMinimumSize(new java.awt.Dimension(270, 50));
        opsReportingTitle.setPreferredSize(new java.awt.Dimension(270, 50));

        reportsAuditLabel.setFont(new java.awt.Font("Arial", 2, 12)); // NOI18N
        reportsAuditLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        reportsAuditLabel.setText("Audit Reports Menu");
        reportsAuditLabel.setMaximumSize(new java.awt.Dimension(125, 25));
        reportsAuditLabel.setMinimumSize(new java.awt.Dimension(125, 25));
        reportsAuditLabel.setPreferredSize(new java.awt.Dimension(125, 25));

        reportsAudit.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        reportsAudit.setText("Audit Report");
        reportsAudit.setToolTipText("");
        reportsAudit.setEnabled(false);
        reportsAudit.setMaximumSize(new java.awt.Dimension(135, 25));
        reportsAudit.setMinimumSize(new java.awt.Dimension(135, 25));
        reportsAudit.setPreferredSize(new java.awt.Dimension(135, 25));

        reportsCustomerLabel.setFont(new java.awt.Font("Arial", 2, 12)); // NOI18N
        reportsCustomerLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        reportsCustomerLabel.setText("Customer Ops Menu");
        reportsCustomerLabel.setMaximumSize(new java.awt.Dimension(125, 25));
        reportsCustomerLabel.setMinimumSize(new java.awt.Dimension(125, 25));
        reportsCustomerLabel.setPreferredSize(new java.awt.Dimension(125, 25));

        customerOps.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        customerOps.setText("Customer Ops");
        customerOps.setToolTipText("");
        customerOps.setMaximumSize(new java.awt.Dimension(135, 25));
        customerOps.setMinimumSize(new java.awt.Dimension(135, 25));
        customerOps.setPreferredSize(new java.awt.Dimension(135, 25));
        customerOps.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                customerOpsMouseClicked(evt);
            }
        });

        reportsEscrowLabel.setFont(new java.awt.Font("Arial", 2, 12)); // NOI18N
        reportsEscrowLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        reportsEscrowLabel.setText("Escrow Reports Menu");
        reportsEscrowLabel.setMaximumSize(new java.awt.Dimension(125, 25));
        reportsEscrowLabel.setMinimumSize(new java.awt.Dimension(125, 25));
        reportsEscrowLabel.setPreferredSize(new java.awt.Dimension(125, 25));

        reportsEscrow.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        reportsEscrow.setText("Escrow Report");
        reportsEscrow.setToolTipText("");
        reportsEscrow.setEnabled(false);
        reportsEscrow.setMaximumSize(new java.awt.Dimension(135, 25));
        reportsEscrow.setMinimumSize(new java.awt.Dimension(135, 25));
        reportsEscrow.setPreferredSize(new java.awt.Dimension(135, 25));

        reportsUserLabel.setFont(new java.awt.Font("Arial", 2, 12)); // NOI18N
        reportsUserLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        reportsUserLabel.setText("User Reports Menu");
        reportsUserLabel.setMaximumSize(new java.awt.Dimension(125, 25));
        reportsUserLabel.setMinimumSize(new java.awt.Dimension(125, 25));
        reportsUserLabel.setPreferredSize(new java.awt.Dimension(125, 25));

        reportsUser.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        reportsUser.setText("User Report");
        reportsUser.setToolTipText("");
        reportsUser.setEnabled(false);
        reportsUser.setMaximumSize(new java.awt.Dimension(135, 25));
        reportsUser.setMinimumSize(new java.awt.Dimension(135, 25));
        reportsUser.setPreferredSize(new java.awt.Dimension(135, 25));

        reportsHelpBtn.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        reportsHelpBtn.setText("Help");
        reportsHelpBtn.setToolTipText("Opens Help");
        reportsHelpBtn.setMaximumSize(new java.awt.Dimension(115, 25));
        reportsHelpBtn.setMinimumSize(new java.awt.Dimension(115, 25));
        reportsHelpBtn.setPreferredSize(new java.awt.Dimension(115, 25));

        javax.swing.GroupLayout opsReportingBtnMnuLayout = new javax.swing.GroupLayout(opsReportingBtnMnu);
        opsReportingBtnMnu.setLayout(opsReportingBtnMnuLayout);
        opsReportingBtnMnuLayout.setHorizontalGroup(
            opsReportingBtnMnuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(opsReportingBtnMnuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(opsReportingBtnMnuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(reportsAuditLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reportsCustomerLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reportsEscrowLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reportsUserLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(opsReportingBtnMnuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(reportsAudit, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reportsEscrow, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reportsUser, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(customerOps, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                .addGap(54, 54, 54))
            .addGroup(opsReportingBtnMnuLayout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(reportsHelpBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        opsReportingBtnMnuLayout.setVerticalGroup(
            opsReportingBtnMnuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(opsReportingBtnMnuLayout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addGroup(opsReportingBtnMnuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(reportsAuditLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reportsAudit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(opsReportingBtnMnuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(customerOps, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reportsCustomerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(opsReportingBtnMnuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(reportsEscrow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reportsEscrowLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(opsReportingBtnMnuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(reportsUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reportsUserLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addComponent(reportsHelpBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout opsReportingLayout = new javax.swing.GroupLayout(opsReporting);
        opsReporting.setLayout(opsReportingLayout);
        opsReportingLayout.setHorizontalGroup(
            opsReportingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(opsReportingLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(opsReportingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(opsReportingBtnMnu, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(opsReportingTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        opsReportingLayout.setVerticalGroup(
            opsReportingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(opsReportingLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(opsReportingTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(opsReportingBtnMnu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        opsGlobalUser.setMaximumSize(new java.awt.Dimension(290, 432));
        opsGlobalUser.setMinimumSize(new java.awt.Dimension(290, 432));
        opsGlobalUser.setPreferredSize(new java.awt.Dimension(290, 432));

        opsGlobalUsersTitle.setFont(new java.awt.Font("Arial", 2, 18)); // NOI18N
        opsGlobalUsersTitle.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        opsGlobalUsersTitle.setText("Global User Operations");
        opsGlobalUsersTitle.setMaximumSize(new java.awt.Dimension(270, 50));
        opsGlobalUsersTitle.setMinimumSize(new java.awt.Dimension(270, 50));
        opsGlobalUsersTitle.setPreferredSize(new java.awt.Dimension(270, 50));

        glbusersAddLabel.setFont(new java.awt.Font("Arial", 2, 12)); // NOI18N
        glbusersAddLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        glbusersAddLabel.setText("Add User(s) to App");
        glbusersAddLabel.setMaximumSize(new java.awt.Dimension(125, 25));
        glbusersAddLabel.setMinimumSize(new java.awt.Dimension(125, 25));
        glbusersAddLabel.setPreferredSize(new java.awt.Dimension(125, 25));

        glbusersAdd.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        glbusersAdd.setText("Add New User(s)");
        glbusersAdd.setToolTipText("");
        glbusersAdd.setMaximumSize(new java.awt.Dimension(135, 25));
        glbusersAdd.setMinimumSize(new java.awt.Dimension(135, 25));
        glbusersAdd.setPreferredSize(new java.awt.Dimension(135, 25));
        glbusersAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                glbusersAddMouseClicked(evt);
            }
        });

        glbusersModifyLabel.setFont(new java.awt.Font("Arial", 2, 12)); // NOI18N
        glbusersModifyLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        glbusersModifyLabel.setText("Modify User(s)");
        glbusersModifyLabel.setMaximumSize(new java.awt.Dimension(125, 25));
        glbusersModifyLabel.setMinimumSize(new java.awt.Dimension(125, 25));
        glbusersModifyLabel.setPreferredSize(new java.awt.Dimension(125, 25));

        glbusersModify.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        glbusersModify.setText("Modify Existing User(s)");
        glbusersModify.setToolTipText("");
        glbusersModify.setEnabled(false);
        glbusersModify.setMaximumSize(new java.awt.Dimension(135, 25));
        glbusersModify.setMinimumSize(new java.awt.Dimension(135, 25));
        glbusersModify.setPreferredSize(new java.awt.Dimension(135, 25));

        glbusersCleanLabel.setFont(new java.awt.Font("Arial", 2, 12)); // NOI18N
        glbusersCleanLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        glbusersCleanLabel.setText("Clean Database");
        glbusersCleanLabel.setMaximumSize(new java.awt.Dimension(125, 25));
        glbusersCleanLabel.setMinimumSize(new java.awt.Dimension(125, 25));
        glbusersCleanLabel.setPreferredSize(new java.awt.Dimension(125, 25));

        glbusersClean.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        glbusersClean.setText("Clean User Database");
        glbusersClean.setToolTipText("");
        glbusersClean.setEnabled(false);
        glbusersClean.setMaximumSize(new java.awt.Dimension(135, 25));
        glbusersClean.setMinimumSize(new java.awt.Dimension(135, 25));
        glbusersClean.setPreferredSize(new java.awt.Dimension(135, 25));

        javax.swing.GroupLayout opsGlobalUserBtnMnuLayout = new javax.swing.GroupLayout(opsGlobalUserBtnMnu);
        opsGlobalUserBtnMnu.setLayout(opsGlobalUserBtnMnuLayout);
        opsGlobalUserBtnMnuLayout.setHorizontalGroup(
            opsGlobalUserBtnMnuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(opsGlobalUserBtnMnuLayout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(opsGlobalUserBtnMnuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, opsGlobalUserBtnMnuLayout.createSequentialGroup()
                        .addComponent(glbusersAddLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(glbusersAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, opsGlobalUserBtnMnuLayout.createSequentialGroup()
                        .addComponent(glbusersModifyLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(glbusersModify, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, opsGlobalUserBtnMnuLayout.createSequentialGroup()
                        .addComponent(glbusersCleanLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(glbusersClean, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        opsGlobalUserBtnMnuLayout.setVerticalGroup(
            opsGlobalUserBtnMnuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(opsGlobalUserBtnMnuLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(opsGlobalUserBtnMnuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(glbusersAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(glbusersAddLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(opsGlobalUserBtnMnuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(glbusersModify, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(glbusersModifyLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(opsGlobalUserBtnMnuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(glbusersClean, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(glbusersCleanLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout opsGlobalUserLayout = new javax.swing.GroupLayout(opsGlobalUser);
        opsGlobalUser.setLayout(opsGlobalUserLayout);
        opsGlobalUserLayout.setHorizontalGroup(
            opsGlobalUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(opsGlobalUserLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(opsGlobalUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(opsGlobalUserBtnMnu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(opsGlobalUsersTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        opsGlobalUserLayout.setVerticalGroup(
            opsGlobalUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(opsGlobalUserLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(opsGlobalUsersTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(opsGlobalUserBtnMnu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(217, 217, 217))
        );

        opsUsersTitle.setFont(new java.awt.Font("Arial", 2, 18)); // NOI18N
        opsUsersTitle.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        opsUsersTitle.setText("User Operations");
        opsUsersTitle.setMaximumSize(new java.awt.Dimension(270, 50));
        opsUsersTitle.setMinimumSize(new java.awt.Dimension(270, 50));
        opsUsersTitle.setPreferredSize(new java.awt.Dimension(270, 50));

        opsUserBtnMnu.setMaximumSize(new java.awt.Dimension(290, 432));
        opsUserBtnMnu.setMinimumSize(new java.awt.Dimension(290, 432));

        userChangePwd.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        userChangePwd.setText("Change Password");
        userChangePwd.setToolTipText("");
        userChangePwd.setEnabled(false);
        userChangePwd.setMaximumSize(new java.awt.Dimension(135, 25));
        userChangePwd.setMinimumSize(new java.awt.Dimension(135, 25));
        userChangePwd.setPreferredSize(new java.awt.Dimension(135, 25));

        userChangePwd1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        userChangePwd1.setText("Update Email Address");
        userChangePwd1.setToolTipText("");
        userChangePwd1.setEnabled(false);
        userChangePwd1.setMaximumSize(new java.awt.Dimension(135, 25));
        userChangePwd1.setMinimumSize(new java.awt.Dimension(135, 25));
        userChangePwd1.setPreferredSize(new java.awt.Dimension(135, 25));

        javax.swing.GroupLayout opsUserBtnMnuLayout = new javax.swing.GroupLayout(opsUserBtnMnu);
        opsUserBtnMnu.setLayout(opsUserBtnMnuLayout);
        opsUserBtnMnuLayout.setHorizontalGroup(
            opsUserBtnMnuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(opsUserBtnMnuLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(opsUserBtnMnuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(userChangePwd1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(opsUserBtnMnuLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(userChangePwd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        opsUserBtnMnuLayout.setVerticalGroup(
            opsUserBtnMnuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(opsUserBtnMnuLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(userChangePwd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(userChangePwd1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout opsUserLayout = new javax.swing.GroupLayout(opsUser);
        opsUser.setLayout(opsUserLayout);
        opsUserLayout.setHorizontalGroup(
            opsUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(opsUserLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(opsUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(opsUserBtnMnu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(opsUsersTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        opsUserLayout.setVerticalGroup(
            opsUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(opsUserLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(opsUsersTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(opsUserBtnMnu, javax.swing.GroupLayout.PREFERRED_SIZE, 119, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout opsContentLayout = new javax.swing.GroupLayout(opsContent);
        opsContent.setLayout(opsContentLayout);
        opsContentLayout.setHorizontalGroup(
            opsContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(opsContentLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(opsEscrow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addComponent(opsReporting, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64)
                .addGroup(opsContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(opsGlobalUser, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE)
                    .addComponent(opsUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        opsContentLayout.setVerticalGroup(
            opsContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, opsContentLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(opsContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, opsContentLayout.createSequentialGroup()
                        .addGroup(opsContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(opsEscrow, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(opsReporting, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(opsGlobalUser, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(opsContentLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(opsUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        opsFooter.setBackground(new java.awt.Color(229, 234, 237));
        opsFooter.setMaximumSize(new java.awt.Dimension(1078, 36));
        opsFooter.setMinimumSize(new java.awt.Dimension(1078, 36));
        opsFooter.setPreferredSize(new java.awt.Dimension(1078, 36));

        statusBar.setBackground(new java.awt.Color(229, 234, 237));
        statusBar.setBorder(null);
        statusBar.setFloatable(false);
        statusBar.setRollover(true);
        statusBar.setMaximumSize(new java.awt.Dimension(1078, 36));
        statusBar.setMinimumSize(new java.awt.Dimension(1078, 36));
        statusBar.setOpaque(false);
        statusBar.setPreferredSize(new java.awt.Dimension(1078, 36));

        LocalDate date = LocalDate.now();
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("MM/dd/yyy");
        statbarDate.setText(" System Date: "+date.format(dtf));
        statbarDate.setBackground(new java.awt.Color(229, 234, 237));
        statbarDate.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        statusBar.add(statbarDate);
        statusBar.add(jSeparator1);

        int delay = 10;
        ActionListener taskPerformer = new ActionListener(){
            public void actionPerformed(ActionEvent evt){
                String sysTime = new java.text.SimpleDateFormat("HH:mm:ss").format(new java.util.Date(System.currentTimeMillis()));
                statbarTime.setText(" System Time: "+sysTime);
            }
        };
        new Timer(delay, taskPerformer).start();
        statbarTime.setBackground(new java.awt.Color(229, 234, 237));
        statbarTime.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        statusBar.add(statbarTime);
        statusBar.add(jSeparator2);

        dispUsername.setBackground(new java.awt.Color(229, 234, 237));
        dispUsername.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        dispUsername.setText("<Username_Placeholder>");
        statusBar.add(dispUsername);
        statusBar.add(jSeparator4);

        logoutButton.setBackground(new java.awt.Color(229, 234, 237));
        logoutButton.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        logoutButton.setText("Logout");
        logoutButton.setFocusable(false);
        logoutButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        logoutButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        logoutButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutButtonMouseClicked(evt);
            }
        });
        statusBar.add(logoutButton);

        javax.swing.GroupLayout opsFooterLayout = new javax.swing.GroupLayout(opsFooter);
        opsFooter.setLayout(opsFooterLayout);
        opsFooterLayout.setHorizontalGroup(
            opsFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, opsFooterLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(statusBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        opsFooterLayout.setVerticalGroup(
            opsFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(statusBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout opsEncapsulationLayout = new javax.swing.GroupLayout(opsEncapsulation);
        opsEncapsulation.setLayout(opsEncapsulationLayout);
        opsEncapsulationLayout.setHorizontalGroup(
            opsEncapsulationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, opsEncapsulationLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(opsFooter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(opsEncapsulationLayout.createSequentialGroup()
                .addComponent(opsHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(opsEncapsulationLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(opsContent, javax.swing.GroupLayout.PREFERRED_SIZE, 1058, Short.MAX_VALUE)
                .addContainerGap())
        );
        opsEncapsulationLayout.setVerticalGroup(
            opsEncapsulationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(opsEncapsulationLayout.createSequentialGroup()
                .addComponent(opsHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(opsContent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(opsFooter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        opsMenu.setBackground(new java.awt.Color(229, 234, 237));
        opsMenu.setMaximumSize(new java.awt.Dimension(101, 22));

        fileMenu.setText("File");

        changeCommit.setText("Commit Changes");
        changeCommit.setEnabled(false);
        fileMenu.add(changeCommit);
        fileMenu.add(fileSeparator);

        menuLogout.setText("Exit Application");
        menuLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuLogoutMouseClicked(evt);
            }
        });
        fileMenu.add(menuLogout);

        opsMenu.add(fileMenu);

        editMenu.setText("Edit");

        jdbcTest.setText("Test JDBC Connection");
        jdbcTest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jdbcTestActionPerformed(evt);
            }
        });
        editMenu.add(jdbcTest);

        ftpTest.setText("Test FTP Connection");
        ftpTest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ftpTestActionPerformed(evt);
            }
        });
        editMenu.add(ftpTest);

        opsMenu.add(editMenu);

        helpMenu.setText("Help");

        helpAbout.setText("About...");
        helpMenu.add(helpAbout);
        helpMenu.add(helpSeparator);

        helpWebHelp.setText("Help...");
        helpMenu.add(helpWebHelp);

        opsMenu.add(helpMenu);

        setJMenuBar(opsMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(opsEncapsulation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(opsEncapsulation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jdbcTestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jdbcTestActionPerformed
        new Thread (() -> {
            ValidateConnections validateJDBC = new ValidateConnections();
            validateJDBC.testJDBCConnection();
        }).start();
    }//GEN-LAST:event_jdbcTestActionPerformed

    private void escrowIL10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_escrowIL10MouseClicked
        Thread ilmenu = new Thread(() -> {
            javax.swing.JFrame il10ops;
            il10ops = new InfoLeaseOperations();
            il10ops.setLocationRelativeTo(null);
            il10ops.setVisible(true);
            il10ops.setDefaultCloseOperation(javax.swing.JFrame.DISPOSE_ON_CLOSE);
            il10ops.pack();
        });
        ilmenu.start();
        this.setVisible(false);
        
    }//GEN-LAST:event_escrowIL10MouseClicked

    private void glbusersAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_glbusersAddMouseClicked
        Thread usrmenu = new Thread(() -> {
            javax.swing.JFrame useradd;
            useradd = new AddUser();
            useradd.setLocationRelativeTo(null);
            useradd.setVisible(true);
            useradd.setDefaultCloseOperation(javax.swing.JFrame.DISPOSE_ON_CLOSE);
            useradd.pack();
        });
        usrmenu.start();       
        this.setVisible(false);
    }//GEN-LAST:event_glbusersAddMouseClicked

    private void menuLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuLogoutMouseClicked
        javax.swing.JFrame usrlog;
        usrlog = new UserLogin();
        usrlog.setLocationRelativeTo(null);
        usrlog.setVisible(true);
        usrlog.setDefaultCloseOperation(EXIT_ON_CLOSE);
        usrlog.pack();
        this.dispose();
    }//GEN-LAST:event_menuLogoutMouseClicked

    private void ftpTestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ftpTestActionPerformed
        new Thread(() -> {
            ValidateConnections ftpTest = new ValidateConnections();
            ftpTest.testFTPConnection();
        }).start();
    }//GEN-LAST:event_ftpTestActionPerformed

    private void logoutButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutButtonMouseClicked
        javax.swing.JFrame logout;
        logout = new UserLogin();
        logout.setLocationRelativeTo(null);
        logout.setVisible(true);
        logout.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        logout.pack();
        this.dispose();
    }//GEN-LAST:event_logoutButtonMouseClicked

    private void customerOpsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_customerOpsMouseClicked
        Object[] options = {"Add Customer(s)","Modify Customer(s)","Browse Customer Record(s)"};
        int i = javax.swing.JOptionPane.showOptionDialog(null,"Please select from the following options","Customer Operations Gateway",javax.swing.JOptionPane.DEFAULT_OPTION,javax.swing.JOptionPane.QUESTION_MESSAGE,null,options,options[2]);
        switch (i) {
            case 0:
                new Thread(() -> {
                    javax.swing.JFrame addcustomer;
                    addcustomer = new AddCustomer();
                    addcustomer.setLocationRelativeTo(null);
                    addcustomer.setVisible(true);
                    addcustomer.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
                    addcustomer.pack();
                    this.dispose(); 
                }).start();               
                break;
            case 1:
                new Thread(() -> {
                    javax.swing.JFrame custmod;
                    custmod = new ModifyCustomer();
                    custmod.setLocationRelativeTo(null);
                    custmod.setVisible(true);
                    custmod.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
                    custmod.pack();
                    this.dispose();
                }).start();               
                break;
            default:
                new Thread(() -> {
                    javax.swing.JFrame custsearch;
                    custsearch = new BrowseCustomer();
                    custsearch.setLocationRelativeTo(null);
                    custsearch.setVisible(true);                   
                    custsearch.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
                    custsearch.setVisible(true);
                    custsearch.pack();
                    this.dispose();
                }).start();                
                break;
        }
    }//GEN-LAST:event_customerOpsMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OperationsMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OperationsMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OperationsMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OperationsMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new OperationsMenu().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel appTitle;
    private javax.swing.JLabel btnLabelAllProd;
    private javax.swing.JLabel btnLabelIAQE;
    private javax.swing.JLabel btnLabelIL10;
    private javax.swing.JLabel btnLabelIL9;
    private javax.swing.JLabel btnLabelLegacy;
    private javax.swing.JLabel btnLabelRapport;
    private javax.swing.JMenuItem changeCommit;
    private javax.swing.JButton customerOps;
    public javax.swing.JLabel dispUsername;
    private javax.swing.JMenu editMenu;
    private javax.swing.JButton escrowAllProducts;
    private javax.swing.JButton escrowHelpBtn;
    private javax.swing.JButton escrowIAQE;
    private javax.swing.JButton escrowIL10;
    private javax.swing.JButton escrowIL9;
    private javax.swing.JButton escrowLegacy;
    private javax.swing.JButton escrowRapport;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JPopupMenu.Separator fileSeparator;
    private javax.swing.JMenuItem ftpTest;
    private javax.swing.JButton glbusersAdd;
    private javax.swing.JLabel glbusersAddLabel;
    private javax.swing.JButton glbusersClean;
    private javax.swing.JLabel glbusersCleanLabel;
    private javax.swing.JButton glbusersModify;
    private javax.swing.JLabel glbusersModifyLabel;
    private javax.swing.JMenuItem helpAbout;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JPopupMenu.Separator helpSeparator;
    private javax.swing.JMenuItem helpWebHelp;
    private javax.swing.JLabel idsLogo;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JMenuItem jdbcTest;
    private javax.swing.JButton logoutButton;
    private javax.swing.JMenuItem menuLogout;
    private javax.swing.JPanel opsContent;
    private javax.swing.JPanel opsEncapsulation;
    private javax.swing.JPanel opsEscrow;
    private javax.swing.JPanel opsEscrowBtnMnu;
    private javax.swing.JLabel opsEscrowTitle;
    private javax.swing.JPanel opsFooter;
    private javax.swing.JPanel opsGlobalUser;
    private javax.swing.JPanel opsGlobalUserBtnMnu;
    private javax.swing.JLabel opsGlobalUsersTitle;
    private javax.swing.JPanel opsHeader;
    private javax.swing.JMenuBar opsMenu;
    private javax.swing.JPanel opsReporting;
    private javax.swing.JPanel opsReportingBtnMnu;
    private javax.swing.JLabel opsReportingTitle;
    private javax.swing.JPanel opsUser;
    private javax.swing.JPanel opsUserBtnMnu;
    private javax.swing.JLabel opsUsersTitle;
    private javax.swing.JButton reportsAudit;
    private javax.swing.JLabel reportsAuditLabel;
    private javax.swing.JLabel reportsCustomerLabel;
    private javax.swing.JButton reportsEscrow;
    private javax.swing.JLabel reportsEscrowLabel;
    private javax.swing.JButton reportsHelpBtn;
    private javax.swing.JButton reportsUser;
    private javax.swing.JLabel reportsUserLabel;
    private javax.swing.JLabel statbarDate;
    private javax.swing.JLabel statbarTime;
    private javax.swing.JToolBar statusBar;
    private javax.swing.JButton userChangePwd;
    private javax.swing.JButton userChangePwd1;
    // End of variables declaration//GEN-END:variables
}
